/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leaveManagementSystem;
import java.sql.*;

import java.awt.Toolkit;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author Anojithan
 */
public class addManager extends javax.swing.JFrame {

    private String AdminName;
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement  pst=null;
    
    
    String FirstName;
    String LastName;
    String UserName;
    String Password;
    String ContactNumber;
    String Address;
    String District;
    String Sex;
    String City;
    String DateOfBirth;
    String DateOfJoined;
    String Email;
    
    
    /**
     * Creates new form login
     */
    public addManager() {
        //this.setUndecorated(true);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        
       addManager_Class manager_class=new addManager_Class();
       txt_ManagerID.setText(manager_class.getID());
            
    }
    
    
    public addManager(String AdminName)
    {
        this.AdminName=AdminName;
        initComponents();
        lb_UserName.setText(this.AdminName);
        conn=Connect.ConnectDB();
        
        try
        {
            
           
            String SqlQuery="SELECT ManagerID from manager order by ManagerID desc LIMIT 1 " ;
            pst=conn.prepareStatement(SqlQuery);
            rs=pst.executeQuery();
            
            
            if(rs.next())
            {
                String ManagerId="";
                System.out.println(ManagerId);
                String empS=rs.getString("ManagerID");
               
                int emp=Integer.parseInt(empS.substring(3))+1;
                String insert="MAA"+emp;
                ManagerId=insert;
                txt_ManagerID.setText(ManagerId);
                System.out.println(ManagerId);
                
            
            }
 
        }
        
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_City = new javax.swing.JTextField();
        bt_Add = new javax.swing.JButton();
        txt_FirstName = new javax.swing.JTextField();
        txt_LastName = new javax.swing.JTextField();
        txt_ManagerID = new javax.swing.JTextField();
        txt_UserName = new javax.swing.JTextField();
        txt_Password = new javax.swing.JTextField();
        txt_ContactNumber = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_District = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_Address = new javax.swing.JTextField();
        bt_Exit = new javax.swing.JButton();
        com_Sex = new javax.swing.JComboBox();
        com_YearOfJoined = new javax.swing.JComboBox();
        com_DateOfBirth = new javax.swing.JComboBox();
        com_MonthOfBirth = new javax.swing.JComboBox();
        com_BirthOfYear = new javax.swing.JComboBox();
        com_DateOfJoined = new javax.swing.JComboBox();
        com_MonthOfJoined = new javax.swing.JComboBox();
        bt_Reset = new javax.swing.JButton();
        bt_Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lb_UserName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lb_LogOut = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("City");
        jPanel9.add(jLabel6);
        jLabel6.setBounds(110, 410, 40, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText(":");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(210, 410, 10, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Last Name");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(90, 90, 90, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Manager ID");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(90, 130, 90, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("User name");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(90, 170, 90, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Password");
        jPanel9.add(jLabel12);
        jLabel12.setBounds(90, 210, 80, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Contact No");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(90, 250, 80, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Address");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(90, 290, 60, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Address");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(110, 330, 70, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("District");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(110, 370, 60, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("First Name");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(90, 50, 90, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText(":");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(210, 50, 10, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText(":");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(210, 90, 10, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText(":");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(210, 130, 10, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText(":");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(210, 170, 10, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText(":");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(210, 210, 10, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText(":");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(210, 250, 10, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText(":");
        jPanel9.add(jLabel26);
        jLabel26.setBounds(210, 330, 10, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText(":");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(210, 370, 10, 20);

        txt_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CityActionPerformed(evt);
            }
        });
        jPanel9.add(txt_City);
        txt_City.setBounds(240, 410, 220, 30);

        bt_Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Add.setText("Add");
        bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddActionPerformed(evt);
            }
        });
        jPanel9.add(bt_Add);
        bt_Add.setBounds(930, 413, 90, 30);

        txt_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FirstNameActionPerformed(evt);
            }
        });
        jPanel9.add(txt_FirstName);
        txt_FirstName.setBounds(240, 50, 220, 30);

        txt_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LastNameActionPerformed(evt);
            }
        });
        jPanel9.add(txt_LastName);
        txt_LastName.setBounds(240, 90, 220, 30);

        txt_ManagerID.setEditable(false);
        txt_ManagerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ManagerIDActionPerformed(evt);
            }
        });
        jPanel9.add(txt_ManagerID);
        txt_ManagerID.setBounds(240, 130, 220, 30);

        txt_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserNameActionPerformed(evt);
            }
        });
        jPanel9.add(txt_UserName);
        txt_UserName.setBounds(240, 170, 220, 30);

        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        jPanel9.add(txt_Password);
        txt_Password.setBounds(240, 210, 220, 30);

        txt_ContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContactNumberActionPerformed(evt);
            }
        });
        jPanel9.add(txt_ContactNumber);
        txt_ContactNumber.setBounds(240, 250, 220, 30);

        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        jPanel9.add(txt_Email);
        txt_Email.setBounds(750, 180, 300, 30);

        txt_District.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DistrictActionPerformed(evt);
            }
        });
        jPanel9.add(txt_District);
        txt_District.setBounds(240, 370, 220, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Date of Birth");
        jPanel9.add(jLabel28);
        jLabel28.setBounds(580, 50, 90, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Date joined");
        jPanel9.add(jLabel29);
        jLabel29.setBounds(580, 90, 90, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Sex");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(580, 140, 90, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("E-mail");
        jPanel9.add(jLabel32);
        jLabel32.setBounds(580, 180, 80, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText(":");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(700, 180, 10, 20);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText(":");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(700, 140, 10, 20);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText(":");
        jPanel9.add(jLabel36);
        jLabel36.setBounds(700, 90, 10, 20);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText(":");
        jPanel9.add(jLabel37);
        jLabel37.setBounds(700, 50, 10, 20);

        txt_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddressActionPerformed(evt);
            }
        });
        jPanel9.add(txt_Address);
        txt_Address.setBounds(240, 330, 220, 30);

        bt_Exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Exit.setText("Exit");
        bt_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExitActionPerformed(evt);
            }
        });
        jPanel9.add(bt_Exit);
        bt_Exit.setBounds(1171, 413, 90, 30);

        com_Sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        com_Sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_SexActionPerformed(evt);
            }
        });
        jPanel9.add(com_Sex);
        com_Sex.setBounds(750, 140, 100, 30);

        com_YearOfJoined.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", " " }));
        com_YearOfJoined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_YearOfJoinedActionPerformed(evt);
            }
        });
        jPanel9.add(com_YearOfJoined);
        com_YearOfJoined.setBounds(950, 90, 100, 30);

        com_DateOfBirth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        com_DateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_DateOfBirthActionPerformed(evt);
            }
        });
        jPanel9.add(com_DateOfBirth);
        com_DateOfBirth.setBounds(750, 50, 60, 30);

        com_MonthOfBirth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));
        com_MonthOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_MonthOfBirthActionPerformed(evt);
            }
        });
        jPanel9.add(com_MonthOfBirth);
        com_MonthOfBirth.setBounds(830, 50, 100, 30);

        com_BirthOfYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", " " }));
        com_BirthOfYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_BirthOfYearActionPerformed(evt);
            }
        });
        jPanel9.add(com_BirthOfYear);
        com_BirthOfYear.setBounds(950, 50, 100, 30);

        com_DateOfJoined.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        com_DateOfJoined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_DateOfJoinedActionPerformed(evt);
            }
        });
        jPanel9.add(com_DateOfJoined);
        com_DateOfJoined.setBounds(750, 90, 60, 30);

        com_MonthOfJoined.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));
        com_MonthOfJoined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_MonthOfJoinedActionPerformed(evt);
            }
        });
        jPanel9.add(com_MonthOfJoined);
        com_MonthOfJoined.setBounds(830, 90, 100, 30);

        bt_Reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Reset.setText("Reset");
        bt_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ResetActionPerformed(evt);
            }
        });
        jPanel9.add(bt_Reset);
        bt_Reset.setBounds(1050, 413, 90, 30);

        bt_Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Back.setText("Back");
        bt_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BackActionPerformed(evt);
            }
        });
        jPanel9.add(bt_Back);
        bt_Back.setBounds(805, 413, 90, 30);

        jLabel3.setText("jLabel3");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(360, 180, 34, 14);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(50, 190, 1280, 460);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        lb_UserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_UserName.setText("User Name");
        jPanel3.add(lb_UserName);
        lb_UserName.setBounds(20, 0, 80, 30);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("User Name");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(140, 0, 90, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(990, 60, 250, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(1110, 60, 130, 30);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/user.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 120, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1200, 30, 120, 110);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        lb_LogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_LogOut.setText("Logout");
        lb_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_LogOutMouseClicked(evt);
            }
        });
        jPanel5.add(lb_LogOut);
        lb_LogOut.setBounds(110, 0, 60, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1040, 90, 190, 30);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setText("Copyright © 2015 by Hexa Group Ptv Ltd");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(160, 10, 450, 30);
        jPanel8.add(jPanel6);
        jPanel6.setBounds(40, 240, 10, 10);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(270, 690, 820, 50);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(null);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/logoSmall.png"))); // NOI18N
        jPanel7.add(jLabel21);
        jLabel21.setBounds(70, 0, 350, 110);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(40, 30, 500, 110);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft Uighur", 1, 70)); // NOI18N
        jLabel2.setText("Add Manger");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 10, 510, 110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(450, 30, 490, 110);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/addDetail.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_LogOutMouseClicked
        // TODO add your handling code here:
        this.hide();
        new login().setVisible(true);
    }//GEN-LAST:event_lb_LogOutMouseClicked

    private void bt_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BackActionPerformed
        // TODO add your handling code here:
        this.hide();
        new OptionAdmin(AdminName).setVisible(true);
    }//GEN-LAST:event_bt_BackActionPerformed

    private void bt_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ResetActionPerformed
        // TODO add your handling code here:
        txt_LastName.setText(null);
        txt_FirstName.setText(null);
        txt_UserName.setText(null);
        txt_Password.setText(null);
        txt_ContactNumber.setText(null);
        txt_Address.setText(null);
        txt_District.setText(null);
        txt_City.setText(null);
        txt_Email.setText(null);
    }//GEN-LAST:event_bt_ResetActionPerformed

    private void com_MonthOfJoinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_MonthOfJoinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_MonthOfJoinedActionPerformed

    private void com_DateOfJoinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_DateOfJoinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_DateOfJoinedActionPerformed

    private void com_BirthOfYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_BirthOfYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_BirthOfYearActionPerformed

    private void com_MonthOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_MonthOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_MonthOfBirthActionPerformed

    private void com_DateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_DateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_DateOfBirthActionPerformed

    private void com_YearOfJoinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_YearOfJoinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_YearOfJoinedActionPerformed

    private void com_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_SexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_SexActionPerformed

    private void bt_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExitActionPerformed
        //        this.hide();
        //      new login().setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_bt_ExitActionPerformed

    private void txt_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddressActionPerformed

    private void txt_DistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DistrictActionPerformed

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_ContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContactNumberActionPerformed

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    private void txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserNameActionPerformed

    private void txt_ManagerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ManagerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ManagerIDActionPerformed

    private void txt_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LastNameActionPerformed

    private void txt_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FirstNameActionPerformed

    private void bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddActionPerformed

        //JOptionPane.showMessageDialog(null,FirstName);

        

        String ManagerID;
        FirstName=txt_FirstName.getText();
        LastName=txt_LastName.getText();
        UserName=txt_UserName.getText();
        Password=txt_Password.getText();
        ContactNumber=txt_ContactNumber.getText();
        Address=txt_Address.getText();
        District=txt_District.getText();
        City=txt_City.getText();
        Email=txt_Email.getText();
        Sex=com_Sex.getSelectedItem().toString();
        DateOfBirth=com_DateOfBirth.getSelectedItem().toString()+"/"+com_MonthOfBirth.getSelectedItem()+"/"+com_BirthOfYear.getSelectedItem();//date input
        DateOfJoined=com_DateOfJoined.getSelectedItem().toString()+"/"+com_MonthOfJoined.getSelectedItem()+"/"+com_YearOfJoined.getSelectedItem();//date input

        boolean Status_UserName,Status_Duplicate,Status_Password,Status_FirstName,Status_LastName,Status_ContactNumber,Status_Address,Status_District,Status_City,Status_Email;
        Status_UserName=false;
        if(UserName.length()>=4)
        Status_UserName=true;

        Status_Password=false;
        if(Password.length()>=4)
        Status_Password=true;

        Status_FirstName=Validate.ValidateName(FirstName);
        Status_LastName=Validate.ValidateName(LastName);
        Status_ContactNumber=Validate.ValidateContactNumber(ContactNumber);
        Status_Address=Validate.ValidateAddress(Address);
        Status_District=Validate.ValidateDistrictandCity(District);
        Status_City=Validate.ValidateDistrictandCity(City);
        Status_Email=Validate.ValidateEmail(Email);
        ManagerID=txt_ManagerID.getText();

        if(Status_Duplicate=true&& Status_UserName==true && Status_Password==true && Status_FirstName==true && Status_LastName==true && Status_ContactNumber==true && Status_Address==true && Status_District==true && Status_City==true &&  Status_Email==true)
        {
            JOptionPane.showMessageDialog(null,"Manager "+this.UserName+" added Successfully");

            try
            {
                Statement statement = conn.createStatement();
                //Resultset rs=
                statement.executeUpdate("insert into manager " + " values  ('"+ManagerID+"','"+FirstName+"','"+LastName+"','"+UserName+"','"+Password+"','"+ContactNumber+"','"+Address+"','"+District+"','"+City+"','"+DateOfBirth+"','"+DateOfJoined+"','"+Sex+"','"+Email+"')");
                
                txt_LastName.setText(null);
                txt_FirstName.setText(null);
                txt_UserName.setText(null);
                txt_Password.setText(null);
                txt_ContactNumber.setText(null);
                txt_Address.setText(null);
                txt_District.setText(null);
                txt_City.setText(null);
                txt_Email.setText(null);
            }
            catch(SQLException ex)
            {
                System.out.println("Data base is not connected !!!!!");
            }
            catch(Exception e)
            {
                e.getMessage();
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Data!! \n User name,FirstName,LastName and Password must contain atleast 4 characters \n Contact Number should have minimum of 9 Digits");
           
        }
    }//GEN-LAST:event_bt_AddActionPerformed

    private void txt_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Add;
    private javax.swing.JButton bt_Back;
    private javax.swing.JButton bt_Exit;
    private javax.swing.JButton bt_Reset;
    private javax.swing.JComboBox com_BirthOfYear;
    private javax.swing.JComboBox com_DateOfBirth;
    private javax.swing.JComboBox com_DateOfJoined;
    private javax.swing.JComboBox com_MonthOfBirth;
    private javax.swing.JComboBox com_MonthOfJoined;
    private javax.swing.JComboBox com_Sex;
    private javax.swing.JComboBox com_YearOfJoined;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lb_LogOut;
    private javax.swing.JLabel lb_UserName;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_City;
    private javax.swing.JTextField txt_ContactNumber;
    private javax.swing.JTextField txt_District;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_LastName;
    private javax.swing.JTextField txt_ManagerID;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
