/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leaveManagementSystem;

import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Anojithan
 */
public class login extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement  pst=null;
    
    String EmployeeID;
    String ManagerID;
    
    /**
     * Creates new form login
     */
    public login() {
        conn=Connect.ConnectDB();
        this.setUndecorated(true);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();
        com_Select = new javax.swing.JComboBox();
        bt_Reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_Login = new javax.swing.JButton();
        lb_Validate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/power.PNG"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 0, 40, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(1320, 0, 40, 40);

        txt_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_UserName);
        txt_UserName.setBounds(890, 380, 230, 30);

        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Password);
        txt_Password.setBounds(890, 420, 230, 30);

        com_Select.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        com_Select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Manager", "Employee" }));
        getContentPane().add(com_Select);
        com_Select.setBounds(890, 330, 230, 30);

        bt_Reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Reset.setText("Reset");
        bt_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ResetActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Reset);
        bt_Reset.setBounds(950, 470, 70, 30);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/pic1.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, -20, 300, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1090, 310, 260, 180);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/logo.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 490, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 330, 490, 190);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/line.PNG"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 50, 30, 230);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(640, 260, 20, 280);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(790, 420, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("User name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(790, 380, 80, 30);

        bt_Login.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_Login.setText("Login");
        bt_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Login);
        bt_Login.setBounds(1040, 470, 80, 30);

        lb_Validate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/login1.jpg"))); // NOI18N
        lb_Validate.setText("*");
        getContentPane().add(lb_Validate);
        lb_Validate.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserNameActionPerformed

    private void bt_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LoginActionPerformed
        // TODO add your handling code here:
        int count;
        boolean StatusUsername,Statuspassword;
        String UserName=txt_UserName.getText();
        String Password=txt_Password.getText();
        if(UserName.length()<=2 && Password.length()<=2)
        {
            lb_Validate.setText("Incorrect User name or Password!!");
            JOptionPane.showMessageDialog(null,"Incorrect User name or Password!!");
        }
       
        else
        {
            String Users=com_Select.getSelectedItem().toString();
            Login_Class login_check=new Login_Class(Users,UserName,Password); 
            
            if(Users=="Admin")
            {
                count=login_check.Check_Admin();
            
                if(count==1)
                     {
                  
                        this.hide();
                        new OptionAdmin(UserName).setVisible(true);
                     }
                
                else if(count>1)
                    System.out.println("Error");
                
                else
                    JOptionPane.showMessageDialog(null,"Unauthorized Access");
            }
           
            
            else if(Users=="Manager")
            {
                
               count=login_check.Check_Manager(); 
               if(count==1)
                {
                    this.ManagerID=login_check.ManagerID;
                    this.hide();
                    new OptionManager(UserName,this.ManagerID).setVisible(true);
                    
                }
                
                else if(count>1)
                    JOptionPane.showMessageDialog(null,"Error");
                
                else
                   JOptionPane.showMessageDialog(null,"User Not Found");
                
            }
            
            
            
            else if(Users=="Employee")
            {
                count=login_check.Check_Employee();
                
                if(count==1)
                {
                    this.EmployeeID=login_check.EmployeeID;
                    System.out.println(this.EmployeeID);
                    this.hide();
                    new overView(UserName,this.EmployeeID).setVisible(true);
                }
                
                else if(count>1)
                    JOptionPane.showMessageDialog(null,"Error");
                
                else
                    JOptionPane.showMessageDialog(null,"Not Found");
            }
            
            else
            {
                JOptionPane.showMessageDialog(null,"Your Selecting User is wrong");
            }
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_bt_LoginActionPerformed

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        
    }//GEN-LAST:event_jLabel8MouseEntered

    private void bt_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ResetActionPerformed
        // TODO add your handling code here:
        txt_UserName.setText(null);
        txt_Password.setText(null);
    }//GEN-LAST:event_bt_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Reset;
    private javax.swing.JComboBox com_Select;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lb_Validate;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
