/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leaveManagementSystem;

import java.sql.*;
import java.util.HashMap;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Anojithan
 */
public class OptionAdmin extends javax.swing.JFrame {

    String AdminName;
    String ManagerId;
    int count;
    
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement  pst=null;
    /**
     * Creates new form Option
     */
    public OptionAdmin() {
        //this.setUndecorated(true);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        conn=Connect.ConnectDB();
        
    }
    public OptionAdmin(String AdminName)
    {
        initComponents();
        this.AdminName=AdminName;
        lb_UserName.setText(this.AdminName);
        bt_Remove.setVisible(false);
        bt_Edit.setVisible(false);
        conn=Connect.ConnectDB();
        
        OptionAdmin_Class optionadmin=new OptionAdmin_Class();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_Report = new javax.swing.JButton();
        lb_UserName = new javax.swing.JLabel();
        lb_LockOut = new javax.swing.JLabel();
        txt_generate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bt_generate = new javax.swing.JButton();
        bt_Edit = new javax.swing.JButton();
        bt_Remove = new javax.swing.JButton();
        bt_Search = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bt_Addmanager = new javax.swing.JButton();
        txt_ManagerID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(null);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        bt_Report.setText("I Report");
        bt_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ReportActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Report);
        bt_Report.setBounds(530, 240, 90, 30);

        lb_UserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_UserName.setText("User-name");
        jPanel1.add(lb_UserName);
        lb_UserName.setBounds(610, 10, 80, 30);

        lb_LockOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_LockOut.setText("Logout");
        lb_LockOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_LockOutMouseClicked(evt);
            }
        });
        jPanel1.add(lb_LockOut);
        lb_LockOut.setBounds(700, 10, 60, 30);

        txt_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_generateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_generate);
        txt_generate.setBounds(250, 240, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Enter Employee ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 250, 140, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText(":");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(220, 250, 10, 20);

        bt_generate.setText("Generate");
        bt_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_generateActionPerformed(evt);
            }
        });
        jPanel1.add(bt_generate);
        bt_generate.setBounds(420, 240, 90, 30);

        bt_Edit.setText("Edit");
        bt_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Edit);
        bt_Edit.setBounds(240, 310, 90, 30);

        bt_Remove.setText("Remove");
        bt_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RemoveActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Remove);
        bt_Remove.setBounds(130, 310, 90, 30);

        bt_Search.setText("Search");
        bt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Search);
        bt_Search.setBounds(420, 180, 90, 30);

        jButton2.setText("Search");
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 180, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Manager ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 180, 120, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText(":");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(150, 180, 10, 20);

        bt_Addmanager.setText("Add Manager");
        bt_Addmanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddmanagerActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Addmanager);
        bt_Addmanager.setBounds(350, 310, 120, 30);

        txt_ManagerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ManagerIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ManagerID);
        txt_ManagerID.setBounds(180, 180, 220, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Option for Admin");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 460, 90);

        bt_Exit.setText("Exit");
        bt_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Exit);
        bt_Exit.setBounds(490, 310, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/option.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 790, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 430);

        setBounds(296, 174, 761, 377);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_ExitActionPerformed

    private void txt_ManagerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ManagerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ManagerIDActionPerformed

    private void lb_LockOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_LockOutMouseClicked
        // TODO add your handling code here:
        this.hide();
        new login().setVisible(true);
    }//GEN-LAST:event_lb_LockOutMouseClicked

    private void bt_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditActionPerformed
        // TODO add your handling code here:
        
        ManagerId=txt_ManagerID.getText();
        
        this.hide();
        new EditManager(ManagerId,AdminName,"false").setVisible(true);
        
    }//GEN-LAST:event_bt_EditActionPerformed

    private void bt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SearchActionPerformed

        
        JOptionPane.showMessageDialog(null,"Manager Found");
        ManagerId=txt_ManagerID.getText();
        OptionAdmin_Class optionadmin=new OptionAdmin_Class();
        count=optionadmin.Search_Manager(ManagerId);
       
        if(count==1)
            {
                bt_Remove.setVisible(true);
                bt_Edit.setVisible(true);
            }
        else if(count>1)
            JOptionPane.showMessageDialog(null,"Error");
                
        else
            JOptionPane.showMessageDialog(null,"Not Found");
       
    }//GEN-LAST:event_bt_SearchActionPerformed

    private void bt_AddmanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddmanagerActionPerformed
        // TODO add your handling code here:
        this.hide();
        new addManager(AdminName).setVisible(true);
    }//GEN-LAST:event_bt_AddmanagerActionPerformed

    private void bt_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RemoveActionPerformed
        // TODO add your handling code here:
        ManagerId=txt_ManagerID.getText();
        OptionAdmin_Class optionadmin=new OptionAdmin_Class();
        optionadmin.Delete_Manager(ManagerId);
        
        
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.hide();
        new login().setVisible(true);
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
    }//GEN-LAST:event_bt_RemoveActionPerformed

    private void txt_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_generateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generateActionPerformed

    private void bt_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_generateActionPerformed
        // TODO add your handling code here:
        
        
        String ID=txt_generate.getText();
        HashMap parameter = new HashMap();
        parameter.put("EMP_ID",ID);
        
        try
        {
            conn=Connect.ConnectDB();
            String path="C:\\Users\\Anojithan\\Documents\\NetBeansProjects\\LeaveManagementSystem\\IReport\\Leave2.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(path);            
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
            JasperViewer.viewReport(jp,false);
        }
        
        catch(JRException ex)
        {
            System.out.println(ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_bt_generateActionPerformed

    private void bt_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ReportActionPerformed
        // TODO add your handling code here:
        try
        {
            conn=Connect.ConnectDB();
            String path="C:\\Users\\Anojithan\\Documents\\NetBeansProjects\\LeaveManagementSystem\\IReport\\Leave1.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(path);            
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp,false);
            
        }
        catch(JRException ex)
        {
            System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_bt_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Addmanager;
    private javax.swing.JButton bt_Edit;
    private javax.swing.JButton bt_Exit;
    private javax.swing.JButton bt_Remove;
    private javax.swing.JButton bt_Report;
    private javax.swing.JButton bt_Search;
    private javax.swing.JButton bt_generate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_LockOut;
    private javax.swing.JLabel lb_UserName;
    private javax.swing.JTextField txt_ManagerID;
    private javax.swing.JTextField txt_generate;
    // End of variables declaration//GEN-END:variables
}
