/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leaveManagementSystem;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Anojithan
 */
public class OptionManager extends javax.swing.JFrame {

    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement  pst=null;
    java.sql.Statement stmt = null;
    int count;
    
    
    
    static boolean Status=false;
    String ManagerName;
    String EmployeeID;
    String ManagerID;
    /**
     * Creates new form Option
     */
    public OptionManager() {
        //this.setUndecorated(true);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        
        conn=Connect.ConnectDB();
    }
    public OptionManager(String ManagerName,String ManagerID)
    {
        initComponents();
        this.ManagerName=ManagerName;
        this.ManagerID=ManagerID;
        lb_UserName.setText(this.ManagerName);
        bt_Remove.setVisible(false);
        bt_Edit.setVisible(false);
        conn=Connect.ConnectDB();
    }
    
    public OptionManager(String ManagerName)
    {
        initComponents();
        lb_UserName.setText(this.ManagerName);
        bt_Remove.setVisible(false);
        bt_Edit.setVisible(false);
        conn=Connect.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lb_UserName = new javax.swing.JLabel();
        lb_LockOut = new javax.swing.JLabel();
        bt_EditMyProfile1 = new javax.swing.JButton();
        bt_EditMyProfile = new javax.swing.JButton();
        bt_Edit = new javax.swing.JButton();
        bt_Remove = new javax.swing.JButton();
        bt_AddEmployee = new javax.swing.JButton();
        bt_Search = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_EmployeeID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        lb_UserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_UserName.setText("User-name");
        jPanel1.add(lb_UserName);
        lb_UserName.setBounds(560, 20, 110, 30);

        lb_LockOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_LockOut.setText("Logout");
        lb_LockOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_LockOutMouseClicked(evt);
            }
        });
        jPanel1.add(lb_LockOut);
        lb_LockOut.setBounds(684, 20, 60, 30);

        bt_EditMyProfile1.setText("Check Leave");
        bt_EditMyProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditMyProfile1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_EditMyProfile1);
        bt_EditMyProfile1.setBounds(180, 230, 120, 30);

        bt_EditMyProfile.setText("Edit My Profile");
        bt_EditMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditMyProfileActionPerformed(evt);
            }
        });
        jPanel1.add(bt_EditMyProfile);
        bt_EditMyProfile.setBounds(340, 310, 120, 30);

        bt_Edit.setText("Edit");
        bt_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Edit);
        bt_Edit.setBounds(230, 310, 90, 30);

        bt_Remove.setText("Remove");
        bt_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RemoveActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Remove);
        bt_Remove.setBounds(120, 310, 90, 30);

        bt_AddEmployee.setText("Add Employee");
        bt_AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(bt_AddEmployee);
        bt_AddEmployee.setBounds(30, 230, 120, 30);

        bt_Search.setText("Search");
        bt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Search);
        bt_Search.setBounds(420, 150, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Employee ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 150, 100, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText(":");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(150, 150, 10, 20);

        txt_EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_EmployeeID);
        txt_EmployeeID.setBounds(180, 150, 220, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Option for Manager");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 460, 90);

        bt_Exit.setText("Exit");
        bt_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Exit);
        bt_Exit.setBounds(480, 310, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leaveManagementSystem/Background/option.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 450);

        setBounds(296, 174, 761, 377);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_ExitActionPerformed

    private void txt_EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmployeeIDActionPerformed

    private void bt_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditActionPerformed
        // TODO add your handling code here:
        this.hide();
        new editEmployee(ManagerName,EmployeeID,"false",ManagerID).setVisible(true);
    }//GEN-LAST:event_bt_EditActionPerformed

    private void bt_AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddEmployeeActionPerformed
        // TODO add your handling code here:
        this.hide();
        new addEmp(ManagerName,ManagerID).setVisible(true);
    }//GEN-LAST:event_bt_AddEmployeeActionPerformed

    private void lb_LockOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_LockOutMouseClicked
        // TODO add your handling code here:
        this.hide();
        new login().setVisible(true);
    }//GEN-LAST:event_lb_LockOutMouseClicked

    private void bt_EditMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditMyProfileActionPerformed
        // TODO add your handling code here:
        this.hide();
        new EditManager(ManagerID,ManagerName,"true").setVisible(true);
    }//GEN-LAST:event_bt_EditMyProfileActionPerformed

    private void bt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SearchActionPerformed
        // TODO add your handling code here:
         EmployeeID=txt_EmployeeID.getText();
        OptionManager_Class optionmanager=new OptionManager_Class();
        count=optionmanager.Search_Employee(EmployeeID);
        if(count==1)
            {
                Status=true;
                JOptionPane.showMessageDialog(null,"Found");
                bt_Remove.setVisible(true);
                bt_Edit.setVisible(true);
            }
                
        else if(count>1)
            JOptionPane.showMessageDialog(null,"Error");
                
        else
            JOptionPane.showMessageDialog(null,"Not Found");
           
        
        
    }//GEN-LAST:event_bt_SearchActionPerformed

    private void bt_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RemoveActionPerformed
        // TODO add your handling code here
        OptionManager_Class optionmanager=new OptionManager_Class();
        optionmanager.RemoveEmployee(EmployeeID);
        JOptionPane.showMessageDialog(null,"Employee Deleted");
        
    }//GEN-LAST:event_bt_RemoveActionPerformed

    private void bt_EditMyProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditMyProfile1ActionPerformed
        this.hide();
        new Approve(ManagerID,ManagerName).setVisible(true);
    }//GEN-LAST:event_bt_EditMyProfile1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_AddEmployee;
    private javax.swing.JButton bt_Edit;
    private javax.swing.JButton bt_EditMyProfile;
    private javax.swing.JButton bt_EditMyProfile1;
    private javax.swing.JButton bt_Exit;
    private javax.swing.JButton bt_Remove;
    private javax.swing.JButton bt_Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_LockOut;
    private javax.swing.JLabel lb_UserName;
    private javax.swing.JTextField txt_EmployeeID;
    // End of variables declaration//GEN-END:variables
}
